services:
  ollama:
    image: ollama/ollama
    entrypoint: ollama serve
    volumes:
      - ollama:/root/.ollama/models
    devices:
      - /dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  runner:
    build:
      context: images/runner
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - ollama


  benchmark:
    build:
      context: images/benchmark
      dockerfile: Dockerfile
    depends_on:
      - ollama

  
  webUi:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui:/app/backend/data 
    ports:
      - 127.0.0.1:80:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434  
    profiles:
      - no-start
    depends_on:
      - ollama

volumes:
  ollama:
  open-webui: 